// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WienCore2019;

namespace WienCore2019.Migrations
{
    [DbContext(typeof(ERPModel2))]
    partial class ERPModel2ModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WienCore2019.Positionen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Anzahl")
                        .HasColumnType("int");

                    b.Property<double?>("Preis")
                        .HasColumnType("float");

                    b.Property<int>("RechnungID")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("RechnungID");

                    b.ToTable("Positionen");
                });

            modelBuilder.Entity("WienCore2019.Rechnung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Datum")
                        .HasColumnType("date");

                    b.Property<int?>("KundenID")
                        .HasColumnType("int");

                    b.Property<double?>("Summe")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Rechnung");
                });

            modelBuilder.Entity("WienCore2019.Positionen", b =>
                {
                    b.HasOne("WienCore2019.Rechnung", "Rechnung")
                        .WithMany("Positionen")
                        .HasForeignKey("RechnungID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
